name: CI

on:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  ventura:
    name: Build (Ventura)
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - name: Build
        uses: actions/checkout@v3
      - run: echo "TAG_VER=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - run: mkdir Output && zip --exclude '*.git*' --exclude '*.github*' --exclude '*Output*' -r -X "Output/${{ github.event.repository.name }}-${TAG_VER}.zip" .  
      
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: Output/*.zip
          
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Output/*.zip
          tag: ${{ github.ref }}
          file_glob: true
