name: CI

on:
  push:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  ventura:
    name: Build (Ventura)
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - name: Build
        uses: actions/checkout@v3
      - run: echo "TAG_VER=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - run: mkdir Output && zip --exclude '*.git*' --exclude '*.github*' --exclude '*Output*' -r -X "Output/${{ github.event.repository.name }}-${TAG_VER}.zip" .  
      
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: Output/*.zip
          
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Output/*.zip
          tag: ${{ github.ref }}
          file_glob: true

  monterey:
    name: Build (Monterey)
    runs-on: macos-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
      - run: echo "TAG_VER=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: "Download latest AirportItlwm for Monterey"
        uses: robinraju/release-downloader@v1.6
        with:
          repository: "OpenIntelWireless/itlwm"
          latest: true
          fileName: "*_Monterey.kext.zip"

      # replace Ventura AirportItlwm with Monterey
      - run: rm -rf OpenCore/EFI/OC/Kexts/AirportItlwm.kext
      - run: unzip *_Monterey.kext.zip
      - run: mv Monterey/AirportItlwm.kext OpenCore/EFI/OC/Kexts/

      # disable Ventura specific patches
      - run: plutil -replace "Booter"."Patch".1."Enabled" -bool false OpenCore/EFI/OC/config.plist
      - run: plutil -replace "Booter"."Patch".2."Enabled" -bool false OpenCore/EFI/OC/config.plist
      - run: plutil -replace "Kernel"."Patch".0."Enabled" -bool false OpenCore/EFI/OC/config.plist
      - run: plutil -replace "Kernel"."Patch".1."Enabled" -bool false OpenCore/EFI/OC/config.plist
      - run: plutil -replace "Kernel"."Patch".2."Enabled" -bool false OpenCore/EFI/OC/config.plist
      - run: plutil -replace "Kernel"."Patch".3."Enabled" -bool false OpenCore/EFI/OC/config.plist
      
      # enable AMFI
      - run: plutil -replace "NVRAM"."Add"."7C436110-AB2A-4BBB-A880-FE41995C9F82"."boot-args" -string "" OpenCore/EFI/OC/config.plist

      # enable SIP
      - run: plutil -replace "NVRAM"."Add"."7C436110-AB2A-4BBB-A880-FE41995C9F82"."csr-active-config" -data AAAAAA== OpenCore/EFI/OC/config.plist

      - run: mkdir Output && zip --exclude '*.git*' --exclude '*.github*' --exclude '*Output*' -r -X "Output/${{ github.event.repository.name }}-${TAG_VER}.zip" .
      
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: Output/*.zip
          
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Output/*.zip
          tag: ${{ github.ref }}
          file_glob: true
